image: gitpod/workspace-python

tasks:
  - init: pip install -r requirements.txt
    command: python main.py

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
